services:
- type: web
  name: Tottenham-Stadium-Events
  plan: free
  runtime: docker
  dockerfilePath: ./Dockerfile 
  envVars:
  - key: API_KEY
    sync: false
  - key: CHROME_BINARY_PATH
    value: /usr/bin/google-chrome
version: "1"
